# Generated by Django 3.1.2 on 2021-01-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_newtopics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTopics',
        ),
    ]
