# Generated by Django 3.1.2 on 2021-02-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_newtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the question', max_length=1000, null=True),
        ),
    ]
