# Generated by Django 3.1.2 on 2021-02-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210227_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
