# Generated by Django 3.1.2 on 2021-03-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210228_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user_id',
        ),
    ]
